### ISSUE TITLE
[META] A32NX Pilot Briefing

### ISSUE THREAD

**Issue by frankkopp** [flybywiresim/docs#102]
## A32NX Pilot Briefing

This shall give the FBW users a good overview of the A32NX cockpit and its functionality as a Flight Crew Operational Manual (FCOM) would.

**Preview Link;** https://docs-git-a32nx-briefing-flybywire.vercel.app/pilots-corner/a32nx-briefing/

### Strategy:

To quickly bring value and content to our users we should:

- Release early, release often
- Continuously improve and extend the content

In simple terms this means get a reasonable MVP (minimal viable product) published quickly then continuously improve based on ideas and feedback from the team and our users.

### 1. Iteration (MVP):

- [x] All pages with a high level overview of the panel/instrument and usage description of buttons/switches/knobs, etc.
  - [x] Rephrasing of texts (#176)
  - [x] Doublecheck which buttons work in the FBW mod and add note if not
  - [x] redo clickable image (new textures from cockpit and background color)
  - [x] Better Tooltips on Flight Deck image map
  - [x] Mobile View does not work with fixed size image
  - [x]  StdBy instruments only contains one standby instrument though...the DCDU is for communicating with atc, and the EFIS terrain radar button is for the ND display ==> change map to SAI only, new for DCDU, and include Terrain in EFIS   

### 2. Iteration

Add sections for Cockpit Instruments:

- [x] ECAM (#116)
- [x] SOP (#47)
- [x] PFD (#177)
- [ ] MCDU (#191)
- [ ] ND
- [ ] ...
 
Add additional features to flight-deck: 

- [ ] Sidestick and Tiller
- [ ] Cross linking of panels (e.g. buttons to screens or messages)
- [ ] Cross linking with Beginner Guide etc.
- [x] Add LVARS/EVENTS for each button/switch/lever

### 3. Iteration

Add details to important aircraft aspects like:
- [ ] ECAM Messages  (#208) 
- [ ] ELEC
- [ ] HYD
- [ ] PNEU
- [ ] ...

**Comment by benw202** [comment]
Going to reserve left of the overhead:

ADIRS Panel
Flight Control Panel Left
Evacuation Panel
Emergency Electric Power Panel
Ground Proximity Warning Panel
Voice Recorder Panel
Oxygen Panel
Calls Panel
Wiper Panel Capt

No PR yet as I have only created a branch for it. I Will comment with a draft PR as soon as the first commit is in!

**Comment by frankkopp** [comment]
Closing this one to track it from now on in the general META Issue and the project board.
