### ISSUE TITLE
[META] Update - Common Issues / FAQ

### ISSUE THREAD

**Issue by Valastiri** [flybywiresim/docs#223]
# Summary

Simple tracking issue to ensure that our common issues page https://docs.flybywiresim.com/fbw-a32nx/support/faq/ is up to date and not duplicating information. 

Another consideration is to move this out of the support directory and directly under -- versions and features -- 
![image](https://user-images.githubusercontent.com/1619968/134262427-2d39c308-b196-4d4e-a74f-7a1132e366f8.png)
- This would sort of provide an easy way for people to quickly look up something they need to read up on and we can internally link to OR offload. 

---

## Changes / Considerations

- [ ] Remove duplicate / out of date questions
- [ ] Ensure page is in sync with Discord / does not overlap Discord #faq channel
- [ ] Consider new format (or keep current one)

Please put suggestions in this meta issue. A PR will be open shortly.
