### ISSUE TITLE
[META] Document breaking changes and fixes to support mkdocs-material v8.0.0

### ISSUE THREAD

**Issue by Valastiri** [flybywiresim/docs#296]
Tracking Meta for issues found with the beta version mkdocs-material

Current Version in testing: `8.0.0b1`

- [x] Custom footer no longer displays "powered by Vercel"
- [x] Custom footer has margin errors
- [x] Announcement bar center styling is now left-aligned
- [x] Tabbed feature -- breaking change
