### ISSUE TITLE
[META] Create Beginner's Guide

### ISSUE THREAD

**Issue by Valastiri** [flybywiresim/docs#53]
## Description

META guide for the A32NX beginners guide section for the docs site. This guide is meant to be beginner friendly and equally as simple to understand for a complete novice. It aims to get the pilot from a `cold & dark` state to performing an ILS landing. 

Each "page" of beginner's guide is listed below with a basic idea of what should be mentioned within the page. Additional content (provided it is within scope) is welcomed by authors.

Images may be required for certain guides to assist in readability and to provide visual references for the end-user. 

The lists provided below can be tackled non-sequentially. As this project develops additional information/requirements for the pages included within are subject to modification. 

For a basic guide and requirements to assist in this META issue, see the [beginner-docs-readme.md](https://github.com/flybywiresim/docs/blob/beginner-guide/beginner-docs-readme.md) in `beginner-guide` branch. 

## Legend

PR status = Page Status
:heavy_exclamation_mark: = PR - Requires Media / Images

## Page Roadmap

This is a basic roadmap of what should be included in the beginner's guide. 

- [x] Starting the Aircraft - (https://github.com/flybywiresim/docs/pull/123) 
	Essentially a Cold and Dark guide. Can reference FBW GS Series.
- [x] Preparing the MCDU - (https://github.com/flybywiresim/docs/pull/58) 
	DIFSRIPP 

- [x] Engine Start and Taxi - (https://github.com/flybywiresim/docs/pull/82) 
	Basic guide to engine start and taxi procedures (including aircraft behavior)
- [x] Takeoff / Climb / Cruise - (https://github.com/flybywiresim/docs/pull/90) 
	How to perform a takeoff, climbing to cruising altitude, and maintaining cruising altitude.
- [x] Descent (Planning up to Final) - (https://github.com/flybywiresim/docs/pull/92)
	Inserting a STAR, relative MCDU features
- [x] Approach and Landing (ILS only) - (https://github.com/flybywiresim/docs/pull/94)
	Performing and accomplishing an approach into an ILS landing.
- [x] On the Ground (After landing up to the gate) - (https://github.com/flybywiresim/docs/pull/54) 
- [x] Powering Down - (https://github.com/flybywiresim/docs/pull/96)

- [x] ~~Glossary of Definitions~~ Retooled into Abbreviations - (https://github.com/flybywiresim/docs/pull/98)
	Providing definitions about Airbus features / commonly used terms in aviation. 

## To Do

- [x] Perform Cleanup
- [ ] Final Review

	 
## Additional Context

If you require assistance feel free to ping or DM on Discord: Valastiri#8902

**Comment by Awemeter** [comment]
> ## Description
> META guide for the A32NX beginners guide section for the docs site. This guide is meant to be beginner friendly and equally as simple to understand for a complete novice. It aims to get the pilot from a `cold & dark` state to performing an ILS landing.
> 
> Each "page" of beginner's guide is listed below with a basic idea of what should be mentioned within the page. Additional content (provided it is within scope) is welcomed by authors.
> 
> Images may be required for certain guides to assist in readability and to provide visual references for the end-user.
> 
> The lists provided below can be tackled non-sequentially. As this project develops additional information/requirements for the pages included within are subject to modification.
> 
> For a basic guide and requirements to assist in this META issue, see the [beginner-docs-readme.md](https://github.com/flybywiresim/docs/blob/beginner-guide/beginner-docs-readme.md) in `beginner-guide` branch.
> 
> ## Legend
> ✔️ = Reviewed and Merged
> ❗ = PR - Requires Media / Images
> 🔶 = In progress / PR in draft
> 
> ## Page Roadmap
> This is a basic roadmap of what should be included in the beginner's guide.
> 
> * [ ]  Starting the Aircraft
>   Essentially a Cold and Dark guide. Can reference FBW GS Series.
> * [ ]  Preparing the MCDU
>   DIFSRIPP
> * [ ]  Engine Start and Taxi
>   Basic guide to engine start and taxi procedures (including aircraft behavior)
> * [ ]  Takeoff / Climb / Cruise
>   How to perform a takeoff, climbing to cruising altitude, and maintaining cruising altitude.
> * [ ]  Descent (Planning up to Final)
>   Inserting a STAR, relative MCDU features
> * [ ]  Approach and Landing (ILS only)
>   Performing and accomplishing an approach into an ILS landing.
> * [ ]  On the Ground (After landing up to the gate)
> * [ ]  Powering Down
> * [ ]  Glossary of Definitions
>   Providing definitions about Airbus features / commonly used terms in aviation.
> 
> ## Additional Context
> If you require assistance feel free to ping or DM on Discord: Valastiri#8902

I have a draft pr for the ground page so you can mark it as WIP #54

**Comment by frankkopp** [comment]
Approach and landing: 
https://github.com/flybywiresim/docs/pull/94

**Comment by frankkopp** [comment]
Powering Down:
https://github.com/flybywiresim/docs/pull/96
