### ISSUE TITLE
[META] Documentation Status Quo and Plan

### ISSUE THREAD

**Issue by Valastiri** [flybywiresim/docs#73]
## Description

The task list below represents pages from the FlyByWire Documentation website.

It shows existing pages (marked complete), pages in development (with PR) and planned pages (marked incomplete).

Contributors can tackle any planned page, create a PR with an empty page describing their intention and start working. 

Please read our documentation for contributing: [Documentation Project](https://docs.flybywiresim.com/dev-corner/development-projects/documentation/)

## Documentation Status Quo and Plan

Suggestions for documentation sections or pages are very welcome. See below for Discord contacts or simply comment on this Issue. 

- [x] Home
- [x] FBW A32NX
  - [x] Versions and Features (regularly updated)
  - [x] Installation
  - [x] Liveries
  - [x] Support
    - [x] Support Guide
    - [x] Reported and Known Issues (constantly updated)
    - [x] Recommended Settings
    - [x] Performance Tips
    - [x] Common Questions and FAQ
  - [x] Feature Guides
    - [x] Throttle Calibration
    - [x] MCDU Keyboard Input
    - [x] FlyByWire and Autoflight 
      - [ ] (needs update)
    - [x] EFB (#195)
    - [x] Simbrief Integration (#224)
    - [x] Fuel and Weight (#217)
    - [x] Freetext (#232)
    - [x] Custom Views (#285) 
    - [ ] ... other selected features
  - [x] A32NX Variable and Events
    - [x] Page with link to github page
    - [x] Common Hardware Mapping Examples (#229)
- [x] Pilot’s Corner
  - [x] Beginner Guide
  - [x] Advanced Guides (#317)
     - [x] TCAS (https://github.com/flybywiresim/docs/pull/472)
     - [x] Holds (https://github.com/flybywiresim/docs/pull/471)
     - [x] Autoland (https://github.com/flybywiresim/docs/pull/390)
  - [x] Airliner Guide
  - [x] A32NX Briefing (tracked here: #102)
    - [x] Flight Deck (#176)
    - [x] Flight-Deck API (#250)
    - [x] ECAM (#116)
      - [ ] ECAM Memos
    - [x] PFD (#177)
    - [ ] ND (https://github.com/flybywiresim/docs/pull/574)
    - [ ] MCDU (#191)
    - [ ] Autoflight
    - [ ] ... additional aircraft documentation
- [x] Development Corner
  - [x] Development Guide (#203)
  - [x] flyPad Development (#194)
  - [x] QA Process (#209)
  - [x] FlyByWire Projects
    - [ ] A32NX Project
    - [ ] Installer Project
    - [x] Documentation Project
    - [x] Website Project 
      - [ ] (might need update)
    - [ ] ACE and MSFS-navdata (#214)
    - [x] Discord Bot (#257)
    - [ ] ... additional FlyByWire projects

Other activities and potential tasks:

- [ ] Potential translation into other languages - on hold for now

## Additional Context

If you require assistance feel free to ping or DM on Discord: 

- Valastiri#8902 
- Cdr_Maverick#6475
