### ISSUE TITLE
[META] Create failures pages

### ISSUE THREAD

**Issue by Valastiri** [flybywiresim/docs#860]
As per the following PR:

- https://github.com/flybywiresim/aircraft/pull/7821

---

We need to document at minimum the following:

- [ ] New EFB page in docs containing information about failures (this page should outline the location - explain the UI and associated functionality.
- [ ] Associated page on symbology associated with the EFB failures page (can be in the flyPAD OS) section or somewhere else in docs (undecided)
- [ ] Image below should be included in text form on a relevant page (undecided).
- [ ] Image below should maybe be restructure to say for more information on symbology to check out our docs page and provide a short link (internal-redirect) to the relevant page.
![image](https://github.com/flybywiresim/docs/assets/1619968/157d0120-5a95-445b-9dab-97dda4fed09c)

Some random notes 

- A lot of our flypad pages are pretty detailed and we should match that format.
- We can also opt to choose to provide more information on various failures and what they entail within the pilot's corner under advanced guides. i.e. failure recovery, what the failure is, what it affects -- this can be done over time and we can provide the framework.

**Comment by Maverickwoe** [comment]
Changed the info page
![image](https://github.com/flybywiresim/docs/assets/12175224/41f8597a-0e79-4155-8e32-7eaddf97b0d9)

**Comment by Maverickwoe** [comment]
Screenshots of the related pages:
Starting page
![image](https://github.com/flybywiresim/docs/assets/12175224/1e78ef60-249e-4e5c-8188-a8e3f34d84e8)

**Comment by Maverickwoe** [comment]
Starting page but empty
![image](https://github.com/flybywiresim/docs/assets/12175224/1becd7e8-bd73-4cec-af87-cf6f9d5c3248)

**Comment by Maverickwoe** [comment]
Starting page with new Generator selection
![image](https://github.com/flybywiresim/docs/assets/12175224/b13465d4-549e-415b-b15d-6ff636419e61)

**Comment by Maverickwoe** [comment]
Starting page with a new generator
![image](https://github.com/flybywiresim/docs/assets/12175224/9963dbc0-96d4-41d4-8967-ab3c619aea47)

**Comment by Maverickwoe** [comment]
Info page
![image](https://github.com/flybywiresim/docs/assets/12175224/2e674d98-4688-42b1-a69b-f0fc2b64d87d)

**Comment by Maverickwoe** [comment]
Altitude generator settings page
![image](https://github.com/flybywiresim/docs/assets/12175224/dcffe8e2-18cd-4f79-8c5d-87ee08adb075)

**Comment by Maverickwoe** [comment]
Probability over time generator settings page
![image](https://github.com/flybywiresim/docs/assets/12175224/ad3ef2d0-bb4e-4deb-b206-73415176ce92)

**Comment by Maverickwoe** [comment]
Speed generator settings page
![image](https://github.com/flybywiresim/docs/assets/12175224/031251d0-0007-40ec-a86f-0be42b30a557)

**Comment by Maverickwoe** [comment]
Speed generator settings page
![image](https://github.com/flybywiresim/docs/assets/12175224/664d4514-c14d-4d18-bbba-5d26e2077a3d)

**Comment by Maverickwoe** [comment]
Timed failure generator settings page
![image](https://github.com/flybywiresim/docs/assets/12175224/26ad1f66-26dc-4425-8856-295097257225)

**Comment by Maverickwoe** [comment]
Take off generator settings page
![image](https://github.com/flybywiresim/docs/assets/12175224/74d857cf-c3b6-46f6-8f69-919e55dc5243)

**Comment by Maverickwoe** [comment]
Failure pool selection page
![image](https://github.com/flybywiresim/docs/assets/12175224/0b881da3-09cc-493e-a98d-6258b69cad80)

**Comment by Maverickwoe** [comment]
![simpletakeoff](https://github.com/flybywiresim/docs/assets/12175224/f3aad9f8-03e6-40f7-ac69-c7c7e8cc7a0a)

**Comment by Maverickwoe** [comment]
**Altitude failure generator:**
This generator triggers a set of failures among the selected failure pool when the airplane reaches a random altitude set between the specified minimum and maximum altitude.
It may be configured either to trigger while the plane climbs or descends.

**Speed failure generator:**
This generator triggers a set of failures among the selected failure pool when the airplane reaches a random speed set between the specified minimum and maximum speed.
It may be configured either to trigger while the plane accelerates or decelerates.

**Timed failure generator:**
This generator triggers a set of failures among the selected failure pool when the time since the arming of the generator reaches a random delay set between the specified minimum and maximum delay.
When configured in the "repeat" or "Once" arming modes, the timer will start right away.
When configured in the "Take Off"  arming, the timer will start once FL or TOGA thrust is set for the first time.

**Probability over time generator:**
At any moment, this generator may trigger a set of failures among the selected failure pool by using the probability specified through the average number of failure per hour.
The mean time to failure (MTTF) is provided as an indication of the delay it may take in average to trigger one failure for the probability of failure per hour.
Note: In aviation rates of failure vary between 10e-3 per hour and 10e-9 per hour depending on the criticality of the system.
For simulation purposes, it is advised to set this value at a much higher level up to 10e-1 (0.1 failure / hour or 1 failure every 10 hours) in order to experience failures once every simulator session.

**Take Off failure generator**
This generator triggers a set of failures among the selected failure pool with a specified probability at each take off.
If a failure will occur during the next take off, it may happen at any moment, during one of these three take off phases:
- Low speed phase : 
The take off phase when the plane exceeds the minimum speed and is slower than the low-med transition speed.
- Medium speed phase :
The take off phase when the plane exceeds the low-med transition speed and is slower than the med-high transition speed.
- High speed & climb phase :
The take off phase when the plane exceeds the med-high transition speed and is lower than the specified height above the runway.
The choice between the 3 phases will be random, using the probability of each phase defined in the settings.

**Rearming options**
Each generator can be configured in the following 4 modes:
OFF : Generator is disabled but settings are kept
ONCE : The generator will trigger a set of failures only once and go to OFF mode
TAKE OFF : The generator will wait until FL or TOGA thrust is set to arm itself. It will trigger a set of failures only once until another take off occurs.
REPEAT : The generator will trigger a set of failures every time the conditions are met.

**max failures and number of failures:**
Each generator may define a specific number of failures to be triggered at the same time.
The set of failures will activate only if the total number of existing failures already occurring on the plane does not exceed the maximum number of failures before their activation.

**Failure pool selection**
Each failure generator allows to select specifically which failures can be triggered. You may select any combination of failures : individual failures, entire systems or all at once. Only a specified number of failures randomly picked in this set will be triggered by the generator.

**Tips:**
You can create several failure generators of the same type so that specific failures may happen at specific conditions different to other set of failures.

**Comment by Maverickwoe** [comment]
See comments that I made on the PR #862
Modifications made to the position of the max number of failures. This setting is now moved inside each generator
