### ISSUE TITLE
[META] Tracking Issue - v0.11.0 Stable Release Notes

### ISSUE THREAD

**Issue by Valastiri** [flybywiresim/docs#866]
Collates new information for release notes and feature write ups

## New Information

- [ ] Navigraph integration changes (simbrief + charts) onboard aircraft - EFB. See the following:
	-  https://github.com/flybywiresim/docs/issues/869
	- PR: https://github.com/flybywiresim/aircraft/pull/8119
- [ ] Automatic callouts EFB
- [ ] SimBridge: Added keyboard shortcut support to remote MCDU 
	- PR: https://github.com/flybywiresim/docs/pull/887
	- SimBridge PR: https://github.com/flybywiresim/simbridge/pull/86
- [ ] Cross Bleed Engine Starts
	- PR: https://github.com/flybywiresim/aircraft/pull/8066
- [ ] Air Conditioning Failures
	- PR: https://github.com/flybywiresim/aircraft/pull/8178
	
## Changes to docs

- [ ] https://github.com/flybywiresim/docs/pull/863 remove flags when moved to stable.
- [ ] Updated EIS standards with wording
	- PR: https://github.com/flybywiresim/aircraft/pull/8205
- [ ] VNAV
